SELECT	PG.IDCODIGOGENERAL,
		A.DESCRIPCION AFP,
		
		PG.A_MATERNO,PG.A_PATERNO,PG.NOMBRES, D.CALCULO, D.VALOR, C.DESCR_CORTA, C.IDTIPOCONCEPTO , C.ORDEN 
FROM deta_movimiento_planilla D
INNER JOIN MOVIMIENTO_PLANILLA MP ON MP.IDMOVIMIENTO= D.IDMOVIMIENTO
INNER JOIN PERSONAL_GENERAL PG ON PG.IDCODIGOGENERAL=MP.IDCODIGOGENERAL
INNER JOIN CONCEPTOS C ON C.IDCONCEPTO = D.IDCONCEPTO
LEFT JOIN AFPS A ON A.IDAFP=MP.IDAFP
WHERE MP.idmovimiento in ('_5SZBJ9J1C8FWAI','_5SQ2WDMVH7J7XN')
AND C.DESCR_CORTA='BASICO'
AND IDTIPOCONCEPTO='IN'